# Generated by Django 5.2.5 on 2025-08-10 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="achieved",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="goal",
            name="achieved_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="goal",
            name="progress",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5
            ),
        ),
    ]
