# Generated by Django 5.2.5 on 2025-08-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_goal_achieved_goal_achieved_date_goal_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="achieved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="goal",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="progress",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
